version: 3

includes:
  project-structure: project-structure.yaml
  airflow: airflow.yaml

tasks:
  all:
    silent: true
    cmds:
      - task: airflow:standalone:activate
      - task: project-structure:activate
