version: 3

includes:
  project-structure: project-structure.yaml
  airflow: airflow.yaml

tasks:
  bashrc:
    silent: true
    status:
      - test ! -f "{{.HOME}}/.bashrc"
    cmds:
      - cat "{{.HOME}}/.bashrc"
  all:
    cmds:
      - task: bashrc
      - task: airflow:activate
