version: 3

vars:
  AIRFLOW_DIR: "{{.ENVIRONMENT_DIR}}/airflow"
  AIRFLOW_HOME: "{{.AIRFLOW_DIR}}"

tasks:
  activate:
    silent: true
    cmds:
      - echo "export AIRFLOW_DIR={{.AIRFLOW_DIR}}"
      - echo "export AIRFLOW_HOME={{.AIRFLOW_HOME}}"
