version: 3

vars:
  AIRFLOW_DIR: "{{.ENVIRONMENT_DIR}}/airflow"
  AIRFLOW_HOME: "{{.AIRFLOW_DIR}}"
  AIRFLOW_VERSION: 2.7.3
  CONSTRAINTS_URL: "https://raw.githubusercontent.com/apache/airflow/constraints-{{.AIRFLOW_VERSION}}/constraints-{{.PYTHON_VERSION}}.txt"

tasks:
  activate:
    silent: true
    cmds:
      - echo "export AIRFLOW_DIR={{.AIRFLOW_DIR}}"
      - echo "export AIRFLOW_HOME={{.AIRFLOW_HOME}}"
      - echo "export AIRFLOW_VERSION={{.AIRFLOW_VERSION}}"
  install:
    silent: true
    cmds:
      - pip install "apache-airflow=={{.AIRFLOW_VERSION}}" --constraint "{{.CONSTRAINTS_URL}}"
